<div style="outline: 2px solid red;padding:10px;border-radius:5px;" data-bind="scope: 'module-a-main'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "module-a-main": {
                        "component": "Magento_Theme/js/test"
                    }
                }
            }
        }
    }
</script>
